<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Scripts\TiendaRopaCano_Database.sql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripts\TiendaRopaCano_Database.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="DbUp-SQLite" Version="6.0.4" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TiendaRopaCano.Domain\TiendaRopaCano.Domain.csproj" />
  </ItemGroup>

</Project>
