<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2024.12.1" />
    <ProjectReference Include="..\TiendaRopaCano.Data\TiendaRopaCano.Data.csproj" />
  </ItemGroup>

</Project>
